### ISSUE TITLE
Check for no non-zero values in HausdorffDistance metrics

### ISSUE THREAD

**Issue by ruefene** [rundherum/pymia#11] opened 2019-02-19 15:15 UTC
When feeding a segmentation or ground-truth mask containing exclusively zero values to the HausdorffDistance metric, an error arises, since there are no distances to compute.
To resolve this issue a check of the number of non-zero values could be implemented, as follows:

```python
    def calculate(self):
        """Calculates the Hausdorff distance."""

        # Check if the both images contain non-zero values
        if np.count_nonzero(sitk.GetArrayFromImage(self.ground_truth)) == 0 or \
                np.count_nonzero(sitk.GetArrayFromImage(self.segmentation)) == 0:
            return float('nan')

        # Compute the Hausdorff distance
        distance_filter = sitk.HausdorffDistanceImageFilter()
        distance_filter.Execute(self.ground_truth, self.segmentation)
        return distance_filter.GetHausdorffDistance()
```

Thank you for correcting this :+1:

**Comment by fabianbalsiger** [comment] 2019-02-19 18:00
Duplicate of #3. Will address this issue within the next two weeks.

**Closed by fabianbalsiger** 2019-02-19 18:00 UTC
Labels: bug, duplicate

**Comment by fabianbalsiger** [comment] 2019-02-20 14:10
@ruefene Issue should be solved, i.e. it will raise a warning and return `float('inf')` in case of zero masks.
Note that I also changed the implementation of the HD. It is now much faster to calculate and you can pass the percentile as an argument: `HausdorffDistance(percentile=95, metric='HDRFDST95')`. Using `HausdorffDistance()` will calculate the full (100 %) Hausdorff distance as previously.
